# Generated by Django 5.2.12 on 2026-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_contact_email_routing'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='plausible_script_url',
            field=models.URLField(blank=True, help_text="Plausible site-specific script URL, e.g. https://plausible.io/js/pa-XXXX.js (copy from Plausible → site settings → install). Preferred over plausible_domain — the site is baked into the URL and it's harder to ad-block. If set, this is used and plausible_domain is ignored."),
        ),
    ]
