# Generated by Django 5.2.12 on 2026-06-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0002_seed_chesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printify_product_id', models.CharField(max_length=50, unique=True)),
                ('blueprint_id', models.IntegerField(help_text='Printify blueprint, e.g. "Unisex Heavy Cotton Tee"')),
                ('print_provider_id', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('description', models.TextField(blank=True, help_text='HTML from Printify; trusted source (own shop)')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('base_retail_price_cents', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True, help_text='Reflects Printify\'s "visible" flag. Hidden products are excluded from /shop/.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0, help_text='Display order; lower first')),
                ('variant_ids', models.JSONField(blank=True, default=list, help_text='Printify variant IDs (ints) this image represents.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printify_variant_id', models.IntegerField()),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(help_text='e.g. "M / Black"', max_length=200)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('price_cents', models.IntegerField()),
                ('cost_cents', models.IntegerField(default=0, help_text='What Printify charges us')),
                ('is_available', models.BooleanField(default=True, help_text='In stock at Printify')),
                ('is_enabled', models.BooleanField(default=True, help_text='Listed for sale; False = soft-deleted')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'size', 'color'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_published'], name='catalog_pro_brand_i_e2dce6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('brand', 'slug')},
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'is_enabled', 'is_available'], name='catalog_var_product_f29638_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'printify_variant_id')},
        ),
    ]
