# Generated by Django 5.2.12 on 2026-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Locally owned draft/publish flag — NOT a mirror of Printify\'s "visible". New imports land as drafts (False); toggle with the Publish / Move-to-draft actions in ct-ops. Only is_published=True products appear on /shop/.'),
        ),
    ]
