# Generated by Django 5.2.12 on 2026-06-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('stripe', 'Stripe'), ('printify', 'Printify')], db_index=True, max_length=20)),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('source', 'event_id')},
            },
        ),
    ]
